import os
import re
import json
from collections import defaultdict

AVERION_DIR = '/home/averion/Averion'
OUTPUT_MD = os.path.join(AVERION_DIR, 'system_map', 'CODEBASE_MAP.md')
OUTPUT_JSON = os.path.join(AVERION_DIR, 'system_map', 'codebase_map.json')

# Find quoted blocks (triple or single-line) that look like real SQL
SQL_BLOCK_PATTERN = re.compile(
    r'''("""|''' + "'''" + r'''|"|')(.*?)\1''',
    re.DOTALL
)
SQL_KEYWORD_CHECK = re.compile(r'\b(SELECT|INSERT|UPDATE|DELETE)\b', re.IGNORECASE)
TABLE_PATTERN = re.compile(r'\b(?:FROM|JOIN|INTO|UPDATE)\s+([a-zA-Z_][a-zA-Z0-9_]*)', re.IGNORECASE)
FUNC_DEF_PATTERN = re.compile(r'^def\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', re.MULTILINE)
IMPORT_PATTERN = re.compile(r'^(?:import|from)\s+([a-zA-Z_][a-zA-Z0-9_]*)', re.MULTILINE)
REDIS_KEY_PATTERN = re.compile(r'''r\.(?:get|set|setex|lpush|rpush|delete|incr|expire|hget|hset)\s*\(\s*f?['"]([^'"]+)['"]''')

SKIP_DIRS = {'.git', '__pycache__', 'node_modules', 'backups', 'venv'}
SKIP_FILES = {'generate_codebase_map.py'}
KNOWN_NON_TABLES = {
    'self', 'cls', 'true', 'false', 'null', 'none', 'now', 'interval',
    'public', 'pg_catalog', 'information_schema',
}

file_data = {}
table_to_files = defaultdict(set)
function_to_file = {}
import_graph = defaultdict(set)

import sys
sys.path.insert(0, AVERION_DIR)
from dotenv import load_dotenv
load_dotenv(os.path.join(AVERION_DIR, '.env'))
import database as db
db.init_pool()
with db.get_db() as _conn:
    _cur = _conn.cursor()
    _cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")
    REAL_TABLES = {row[0].lower() for row in _cur.fetchall()}
print(f"Found {len(REAL_TABLES)} real tables in the database to cross-reference against")

py_files = []
for root, dirs, files in os.walk(AVERION_DIR):
    dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
    for fname in files:
        if fname.endswith('.py') and fname not in SKIP_FILES:
            py_files.append(os.path.join(root, fname))

local_module_names = {os.path.splitext(os.path.basename(p))[0] for p in py_files}

def extract_real_tables(content):
    tables = set()
    for quote_char, block in SQL_BLOCK_PATTERN.findall(content):
        if not SQL_KEYWORD_CHECK.search(block):
            continue
        for t in TABLE_PATTERN.findall(block):
            t_lower = t.lower()
            if t_lower not in REAL_TABLES:
                continue
            tables.add(t_lower)
    return tables

for filepath in sorted(py_files):
    rel_name = os.path.relpath(filepath, AVERION_DIR)
    try:
        with open(filepath, 'r', errors='ignore') as f:
            content = f.read()
    except Exception:
        continue

    tables = extract_real_tables(content)
    functions = FUNC_DEF_PATTERN.findall(content)
    imports_raw = set(IMPORT_PATTERN.findall(content))
    local_imports = imports_raw & local_module_names

    redis_keys = set()
    for m in REDIS_KEY_PATTERN.findall(content):
        normalized = re.sub(r'\{[^}]+\}', '{}', m)
        redis_keys.add(normalized)

    file_data[rel_name] = {
        'tables': sorted(tables),
        'functions': sorted(functions),
        'local_imports': sorted(local_imports),
        'redis_keys': sorted(redis_keys),
        'line_count': content.count('\n'),
    }

    for t in tables:
        table_to_files[t].add(rel_name)
    for fn in functions:
        function_to_file[fn] = rel_name
    for imp in local_imports:
        import_graph[rel_name].add(imp)

os.makedirs(os.path.join(AVERION_DIR, 'system_map'), exist_ok=True)

with open(OUTPUT_JSON, 'w') as f:
    json.dump({
        'files': file_data,
        'table_to_files': {k: sorted(v) for k, v in table_to_files.items()},
    }, f, indent=2)

with open(OUTPUT_MD, 'w') as f:
    f.write("# Averion Codebase Map (auto-generated, do not hand-edit)\n\n")
    f.write("Generated by `generate_codebase_map.py`. Re-run anytime to refresh.\n")
    f.write(f"Scanned {len(file_data)} Python files.\n\n")

    f.write("## Tables touched by very few files (potential drift risk)\n\n")
    f.write("If a table conceptually overlaps with another table touched by many MORE files, that is a red flag worth investigating - exactly the pattern that caused the live_dca_positions vs positions bug.\n\n")
    sparse_tables = sorted(table_to_files.items(), key=lambda x: len(x[1]))
    for table, files in sparse_tables[:40]:
        f.write(f"- **{table}**: {len(files)} file(s) - {', '.join(sorted(files))}\n")
    f.write("\n")

    f.write("## All tables and which files touch them\n\n")
    for table in sorted(table_to_files.keys()):
        files = sorted(table_to_files[table])
        f.write(f"### `{table}` ({len(files)} files)\n")
        for fname in files:
            f.write(f"- {fname}\n")
        f.write("\n")

    f.write("## File-by-file breakdown\n\n")
    for fname in sorted(file_data.keys()):
        d = file_data[fname]
        f.write(f"### {fname} ({d['line_count']} lines)\n")
        if d['tables']:
            f.write(f"- **Tables touched**: {', '.join(d['tables'])}\n")
        if d['local_imports']:
            f.write(f"- **Imports from**: {', '.join(d['local_imports'])}\n")
        if d['functions']:
            f.write(f"- **Functions defined**: {', '.join(d['functions'][:25])}")
            if len(d['functions']) > 25:
                f.write(f" (+{len(d['functions'])-25} more)")
            f.write("\n")
        if d['redis_keys']:
            f.write(f"- **Redis keys used**: {', '.join(d['redis_keys'])}\n")
        f.write("\n")

print(f"Map written to {OUTPUT_MD}")
print(f"JSON written to {OUTPUT_JSON}")
print(f"Total files scanned: {len(file_data)}")
print(f"Total distinct tables found: {len(table_to_files)}")
